# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['ANSIBLE_ROLES_PATH'] = "../../../roles"
ENV['ANSIBLE_RETRY_FILES_SAVE_PATH'] = "retry"
role = File.basename(File.dirname(File.expand_path('..', __FILE__)))
# File.expand_path('..')

boxes = [
  {
    :name => "apt-cacher",
    :box => "ubuntu/trusty64",
    :ip => '192.168.33.254',
    :cpu => "10",
    :ram => "256"
    # :groups => ["apt-cacher-ng-servers"]
  },
]

Vagrant.configure("2") do |config|
  boxes.each do |box|
    config.vm.define box[:name] do |vms|
      vms.vm.box = box[:box]
      vms.vm.box_url = box[:url]
      vms.vm.hostname = "ansible-#{role}-#{box[:name]}"

      vms.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--cpuexecutioncap", box[:cpu]]
        v.name = "ansible-#{role}-#{box[:name]}"
        v.memory = box[:ram]
      end

      vms.vm.network :private_network, ip: box[:ip]

      vms.vm.provision :ansible do |ansible|
        ansible.playbook = "apt-cacher-ng.yml"
        ansible.verbose = "vv"
        # ansible.groups = {
        #   "consul-quorum" => ["logstash"],
        # }
      end
    end
  end
end
